export const TOGGLE_CHAT_RESPONSE_SPINNER = "TOGGLE_CHAT_RESPONSE_SPINNER";
export const TOGGLE_AGENT_CREATE_SPINNER = "TOGGLE_AGENT_CREATE_SPINNER";
export const TOGGLE_EDIT_AGENT_SPINNER = "TOGGLE_EDIT_AGENT_SPINNER";

export const GET_ALL_AGENTS_DATA = "GET_ALL_AGENTS_DATA";
export const GET_AGENT_BY_ID = "GET_AGENT_BY_ID";
export const CREATE_NEW_AGENT = "CREATE_NEW_AGENT";
export const UPDATE_AGENT_DATA = "UPDATE_AGENT_DATA";
export const DELETE_AGENT_DATA = "DELETE_AGENT_DATA";
export const GET_CHAT_RESPONSE = "GET_CHAT_RESPONSE";
