CREATE TABLE [dbo].[NewFeatureRequests]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
	[Title] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[DateCreated] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[CreatedBy] NVARCHAR(MAX) NOT NULL,
	[DateModified] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[ModifiedBy] NVARCHAR(MAX) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
)
GO;

CREATE NONCLUSTERED INDEX ix_NewFeatureRequests_Id_IsActive ON [dbo].[NewFeatureRequests]([Id], [IsActive])
GO;
