export const TOGGLE_WORKSPACES_LOADER = "TOGGLE_WORKSPACES_LOADER";
export const TOGGLE_EDIT_WORKSPACES_LOADER = "TOGGLE_EDIT_WORKSPACES_LOADER";
export const TOGGLE_CREATE_WORKSPACE_LOADER = "TOGGLE_CREATE_WORKSPACE_LOADER";
export const TOGGLE_CREATE_WORKSPACE_DRAWER = "TOGGLE_CREATE_WORKSPACE_DRAWER";
export const TOGGLE_ASSOCIATE_AGENTS_DRAWER = "TOGGLE_ASSOCIATE_AGENTS_DRAWER";

export const GET_ALL_WORKSPACES = "GET_ALL_WORKSPACES";
export const GET_WORKSPACE_BY_ID = "GET_WORKSPACE_BY_ID";
export const ADD_NEW_WORKSPACE_DATA = "ADD_NEW_WORKSPACE_DATA";
export const UPDATE_EXISTING_WORKSPACE_DATA = "UPDATE_EXISTING_WORKSPACE_DATA";
export const DELETE_EXISTING_WORKSPACE_DATA = "DELETE_EXISTING_WORKSPACE_DATA";
export const GET_WORKSPACE_GROUP_CHAT_RESPONSE =
	"GET_WORKSPACE_GROUP_CHAT_RESPONSE";
