export const GET_CONVERSATION_HISTORY = "GET_CONVERSATION_HISTORY";
export const CLEAR_CONVERSATION_HISTORY = "CLEAR_CONVERSATION_HISTORY";

export const CLEAR_WORKSPACE_CONVERSATION_HISTORY =
	"CLEAR_WORKSPACE_CONVERSATION_HISTORY";
export const GET_WORKSPACE_CONVERSATION_HISTORY =
	"GET_WORKSPACE_CONVERSATION_HISTORY";
