export const GET_ALL_BUG_REPORTS = "GET_ALL_BUG_REPORTS";
export const GET_ALL_FEATURE_REQUESTS = "GET_ALL_FEATURE_REQUESTS";
export const IS_ADMIN_ACCESS_ENABLED_FOR_USER =
	"IS_ADMIN_ACCESS_ENABLED_FOR_USER";

export const IS_BUG_REPORT_SPINNER_LOADING = "IS_BUG_REPORT_SPINNER_LOADING";
export const IS_FEATURE_REQUEST_SPINNER_LOADING =
	"IS_FEATURE_REQUEST_SPINNER_LOADING";
export const IS_ADMIN_PAGE_SPINNER_LOADING = "IS_ADMIN_PAGE_SPINNER_LOADING";
