export const TOGGLE_TOOLS_SKILLS_LOADER = "TOGGLE_TOOLS_SKILLS_LOADER";
export const TOGGLE_EDIT_SKILLS_LOADER = "TOGGLE_EDIT_SKILLS_LOADER";
export const TOGGLE_CREATE_SKILLS_LOADER = "TOGGLE_CREATE_SKILLS_LOADER";
export const TOGGLE_MCP_TOOLS_LOADER = "TOGGLE_MCP_TOOLS_LOADER";
export const TOGGLE_ADD_SKILL_DRAWER = "TOGGLE_ADD_SKILL_DRAWER";
export const TOGGLE_MCP_TOOLS_DRAWER = "TOGGLE_MCP_TOOLS_DRAWER";

export const GET_ALL_TOOLS_SKILLS = "GET_ALL_TOOLS_SKILLS";
export const GET_TOOL_SKILL_BY_ID = "GET_TOOL_SKILL_BY_ID";
export const ADD_NEW_TOOL_SKILL = "ADD_NEW_TOOL_SKILL";
export const UPDATE_EXISTING_TOOL_SKILL = "UPDATE_EXISTING_TOOL_SKILL";
export const DELETE_EXISTING_TOOL_SKILL = "DELETE_EXISTING_TOOL_SKILL";
export const GET_ALL_MCP_SERVER_TOOLS = "GET_ALL_MCP_SERVER_TOOLS";
