export const TOGGLE_TOOLS_SKILLS_LOADER = "TOGGLE_TOOLS_SKILLS_LOADER";

export const GET_ALL_TOOLS_SKILLS = "GET_ALL_TOOLS_SKILLS";
export const GET_TOOL_SKILL_BY_ID = "GET_TOOL_SKILL_BY_ID";
export const ADD_NEW_TOOL_SKILL = "ADD_NEW_TOOL_SKILL";
export const UPDATE_EXISTING_TOOL_SKILL = "UPDATE_EXISTING_TOOL_SKILL";
export const DELETE_EXISTING_TOOL_SKILL = "DELETE_EXISTING_TOOL_SKILL";
