export const POLL_NOTIFICATIONS = "POLL_NOTIFICATIONS";
export const RECEIVE_NOTIFICATION = "RECEIVE_NOTIFICATION";
export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ";
export const CLEAR_ALL_NOTIFICATIONS = "CLEAR_ALL_NOTIFICATIONS";

export const TOGGLE_NOTIFICATIONS_LOADER = "TOGGLE_NOTIFICATIONS_LOADER";
export const TOGGLE_NOTIFICATIONS_PANEL = "TOGGLE_NOTIFICATIONS_PANEL";
