export const GET_CHAT_RESPONSE = "GET_CHAT_RESPONSE";
export const CLEAR_CONVERSATION_HISTORY = "CLEAR_CONVERSATION_HISTORY";
export const DIRECT_CHAT_REQUEST = "DIRECT_CHAT_REQUEST";
export const GET_CONVERSATION_HISTORY = "GET_CONVERSATION_HISTORY";
