export const TOGGLE_MAIN_SPINNER = "TOGGLE_MAIN_SPINNER";

export const TOGGLE_NEW_AGENT_DRAWER = "TOGGLE_NEW_AGENT_DRAWER";
export const TOGGLE_AGENTS_LIST_DRAWER = "TOGGLE_AGENTS_LIST_DRAWER";
export const TOGGLE_EDIT_AGENT_DRAWER = "TOGGLE_EDIT_AGENT_DRAWER";
export const TOGGLE_AGENT_TEST_DRAWER = "TOGGLE_AGENT_TEST_DRAWER";
export const TOGGLE_DIRECT_CHAT_DRAWER = "TOGGLE_DIRECT_CHAT_DRAWER";
export const TOGGLE_DIRECT_CHAT_LOADER = "TOGGLE_DIRECT_CHAT_LOADER";
