export const TOGGLE_MAIN_SPINNER = "TOGGLE_MAIN_SPINNER";

export const TOGGLE_NEW_AGENT_DRAWER = "TOGGLE_NEW_AGENT_DRAWER";
export const TOGGLE_AGENTS_LIST_DRAWER = "TOGGLE_AGENTS_LIST_DRAWER";
export const TOGGLE_EDIT_AGENT_DRAWER = "TOGGLE_EDIT_AGENT_DRAWER";
export const TOGGLE_AGENT_TEST_DRAWER = "TOGGLE_AGENT_TEST_DRAWER";
export const TOGGLE_DIRECT_CHAT_DRAWER = "TOGGLE_DIRECT_CHAT_DRAWER";
export const TOGGLE_DIRECT_CHAT_LOADER = "TOGGLE_DIRECT_CHAT_LOADER";
export const TOGGLE_FEEDBACK_DRAWER = "TOGGLE_FEEDBACK_DRAWER";
export const TOGGLE_FEEDBACK_LOADER = "TOGGLE_FEEDBACK_LOADER";

export const GET_ALL_CONFIGURATIONS = "GET_ALL_CONFIGURATIONS";
export const GET_CONFIGURATION_BY_KEY_NAME = "GET_CONFIGURATION_BY_KEY_NAME";
export const ADD_NEW_BUG_REPORT = "ADD_NEW_BUG_REPORT";
export const ADD_NEW_FEATURE_REQUEST = "ADD_NEW_FEATURE_REQUEST";
export const GET_TOP_ACTIVE_AGENTS = "GET_TOP_ACTIVE_AGENTS";
